name: Deploy to Production Environment

on:
 repository_dispatch:
   types: [deploy_to_prod]
   
jobs:
  build:

    env:
     SolutionName: ${{ github.event.client_payload.solutionname }}
     prodCS: ${{ secrets.PROD_ENV_CONNECTION_STRING }}
     requestId: ${{ github.event.client_payload.requestid }}
     POWER_PLATFORM_ACTIONS_SECRET: ${{ secrets.POWER_PLATFORM_ACTIONS_SECRET }}
     projectId: ${{ github.event.client_payload.projectid }}

    runs-on: windows-2019

    steps:
    - name: 'clone this repo'
      uses: actions/checkout@v2-beta

    - name: 'Power ALM Import action Checkout'
      uses: actions/checkout@v2-beta
      with:
        repository: poweralm/import
        ref: refs/heads/master
        token: ${{ env.POWER_PLATFORM_ACTIONS_SECRET }}
        path: .github/import

    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          # Required, workflow file name or ID
          workflow: deploy-PPSolution-to-test.yml

    - name: 'Import the solution to Prod Environment'
      id: import
      uses: ./.github/import
      with:
        ConnectionString: '${{ env.prodCS }}'
        SolutionFile: '${{env.SolutionName}}\${{env.SolutionName}}_managed.zip'
    
    - name: Set job status
      if: always()
      run: |
        $importError = echo "${{ steps.import.outputs.errorMessage }}"
        $errors = @{
          'ImportAction' = "$importError"
        }
        $jobStatus = echo ${{ job.status }}
        $workflow = echo ${{ github.workflow }}
        $run = echo ${{ github.run_id }}
        $requestId = echo ${{ env.requestId }}
        $projectid = echo "${{ env.projectId }}"
        $status = @{
          'status' = $jobStatus;
          'workflow' = "$workflow";
          'branch' = "";
          'run' = $run;
          'requestid' = $requestId;
          'projectid' = "$projectid"
          'errors' = $errors
        }
        $jsonString = ConvertTo-Json -InputObject $status
        $jsonString > status.json

    - name: Update job status
      uses: actions/upload-artifact@v1
      with:
        name: job_status
        path: status.json
  
  notify:
    needs: [build]
    if: always()
    runs-on: windows-latest
    steps:

    - name: Download artifact job_status
      uses: actions/download-artifact@v1
      with:
        name: job_status
      continue-on-error: true

    - name: Reading status & Invoking the webhook
      if: always()
      run: |
        $fileExists = Test-Path job_status/status.json -PathType Leaf
        $uri = echo '${{ github.event.client_payload.webhookurl }}'
        $jsonData = ''
        if ($fileExists) {
          $jsonData = Get-Content job_status/status.json
          echo "Data read from status file :: " $jsonData
        } else {
          $workflow = echo ${{ github.workflow }}
          $repo = echo ${{ github.repository }}
          $run = echo ${{ github.run_id }}
          $requestId = echo ${{ github.event.client_payload.requestid }}
          $projectid = echo "${{ github.event.client_payload.projectid }}"
          $errors = @{
            "Actions"="Unable to get the status file from the previous job"
          }
          $status = @{
            'status' = "$fileExists";
            'workflow' = "$workflow";
            'branch' = "";
            'repo' = $repo;
            'run' = $run;
            'requestid' = $requestId;
            'projectid' = "$projectid";
            'errors' = $errors
          }
          $jsonData = ConvertTo-Json -InputObject $status
          echo "Data constructed as status.json file is not present :: " $jsonData
        }
        echo "Invoking the WebHook Url"
        Invoke-RestMethod -Uri $uri -Body $jsonData  -Method POST -ContentType 'application/json'
        echo "Invoked the WebHook Url"
